campaign_management_task:
  description: >
    As the Campaign Manager, your task is to coordinate the entire content marketing workflow
    according to our established process. You will:

    1. Initiate the market research phase by delegating to the Market Strategist
    2. Review the strategic brief and delegate content creation to the Content Creator
    3. Send the draft content to the Review Agent for quality assurance
    4. If revisions are needed, coordinate between Content Creator and Review Agent
    5. Once approved, delegate formatting to the Content Director
    6. After publication, request performance analysis from the Performance Agent
    7. Based on performance data, decide whether to:
       - Consider the campaign successful if goals are met
       - Request specific optimizations if minor improvements are needed
       - Restart the process if major changes are required

    Your role is to make strategic decisions at each step and ensure the workflow
    proceeds efficiently. The topic for this campaign is: '{topic}'.
  expected_output: >
    A comprehensive report detailing the entire campaign process, decisions made at
    each stage, and final outcomes. Include recommendations for future campaigns
    based on what worked well and what could be improved.
  agent: campaign_manager

market_research_task:
  description: >
    Conduct a comprehensive market analysis for the topic: '{topic}' targeting {target_audience}.
    Your final report should be a detailed brief for the content creation team.
    Use your suite of research tools to gather current data. The current year is {current_year}.

    Focus your research on:
    - Target audience: {target_audience}
    - Distribution channels: {channels}
    - Campaign budget considerations: ${budget}
    - Campaign timeline: {start_date} to {end_date}

    The analysis must include:
    1. **Top 3 Competitors:** Identify who they are and analyze their strategies for {target_audience}
    2. **Trending Topics & Angles:** Current {current_year} trends relevant to {topic} and {target_audience}
    3. **Content Gaps:** What competitors aren't covering for {target_audience} in {current_year}
    4. **Target Audience Profile:** Deep dive into {target_audience} needs, pain points, and preferences
    5. **SEO Keywords:** 10-15 keywords relevant to {topic} and {target_audience}
    6. **Channel-Specific Insights:** Optimization tips for {channels}
  expected_output: >
    A structured markdown document containing the full strategic brief with clear
    sections for Competitor Analysis, {current_year} Trending Topics, Content Gaps, 
    {target_audience} Profile, SEO Keywords, and {channels} Optimization.
  agent: market_strategist

content_creation_task:
  description: >
    Using the strategic brief provided in the context, write a comprehensive and
    engaging blog post on the topic of '{topic}'. The article should be at least
    700 words and targeted specifically at {target_audience}.

    Key requirements:
    - Target the audience profile: {target_audience}
    - Consider the campaign budget of ${budget} when discussing solutions
    - Naturally integrate the recommended SEO keywords
    - Write in the brand voice: '{brand_voice}'
    - Structure for distribution across: {channels}
    - Reference current year {current_year} trends and data
    - Make content relevant for the campaign period ({start_date} to {end_date})

    Ensure the content is optimized for the specified distribution channels and speaks
    directly to the target audience's needs and budget considerations.
  expected_output: >
    The full text of a well-written, 700+ word blog post in markdown format targeting
    {target_audience}. The article should be ready for the editing phase and optimized
    for {channels} distribution.
  agent: content_creator

content_review_task:
  description: >
    Review the blog post provided in the context. Perform a meticulous edit to
    ensure it is perfect and ready for publishing.

    Your review process must include:
    - **Proofreading:** Correct all spelling and grammatical errors.
    - **Clarity & Flow:** Improve sentence structure and readability.
    - **Brand Voice Alignment:** Ensure the tone matches our brand voice: '{brand_voice}'.
    - **Fact-Checking:** Briefly verify any major claims or data points.

    If the content requires significant revisions, clearly indicate what needs to be
    fixed and why, so the Content Creator can make the necessary improvements.
  expected_output: >
    Either:
    1. The final, fully polished, and error-free version of the blog post, as a
       single block of markdown text, OR
    2. A detailed list of required revisions if the content needs significant improvement.
  agent: review_agent

report_formatting_task:
  description: >
    Take the final, polished blog post from the context and format it into a
    complete, professional report.

    You must perform the following actions:
    1.  Create a compelling and SEO-friendly main title for the report.
    2.  Write a 100-word executive summary that goes at the top of the report.
    3.  Format the entire document using clean markdown, including proper headings
        (#, ##), bullet points, and bold text for emphasis.
    4.  Add a "Distribution Channels" section at the end with recommendations for
        where this content should be published (e.g., company blog, LinkedIn, etc.)
  expected_output: >
    A single, clean markdown document containing the final report. The report
    must start with the main title (H1), followed by the executive summary,
    and then the full, formatted article. Do not include '```markdown' or
    any other code block specifiers.
  agent: content_director

performance_analysis_task:
  description: >
    Analyze the performance of the published content and provide optimization
    recommendations. The current year is {current_year} and today's date should be used for the analysis.

    Use the Analytics Tool to get performance data for the content titled: '{topic} Report'

    Your analysis should include:
    1. Key performance metrics (views, engagement rate, conversion rate, etc.)
    2. Comparison against industry benchmarks for {target_audience}
    3. Identification of strengths and weaknesses
    4. Specific optimization recommendations based on the {channels} distribution channels
    5. Decision on whether the content has met its goals within the campaign budget of ${budget}

    Important: Use the current year {current_year} in your analysis and ensure all dates reflect the current time period.
  expected_output: >
    A detailed performance analysis report dated in {current_year} with clear metrics, insights, and
    actionable recommendations. The report should conclude with a definitive
    recommendation: "Success - Goals Met" or "Needs Optimization" with specific
    areas to improve.
  agent: performance_agent
