campaign_management_task:
  description: >
    Lead strategic campaign for '{topic}' targeting {target_audience}.
    Budget: ${budget}, Timeline: {start_date} to {end_date}, Voice: '{brand_voice}'
    
    Coordinate all content creation, ensure quality, and deliver executive campaign strategy.
  expected_output: >
    Executive campaign strategy with performance projections and success framework.
  agent: campaign_manager

market_research_task:
  description: >
    Research and analyze the market for '{topic}' targeting {target_audience}.
    Budget: ${budget}, Timeline: {start_date} to {end_date}, Voice: '{brand_voice}'
    
    **CRITICAL REQUIREMENTS - EXACTLY 3 FILES WITH SPECIFIC NAMES:**
    
    You MUST use the File Writer Tool to create exactly these 3 files:
    
    1. **File: content/{campaign_name}/market_research/competitors.md**
       - Research and list 8+ REAL companies by name in this market
       - Include actual company names like "HubSpot", "Mailchimp", "ActiveCampaign" 
       - Add market position, key strengths, pricing, AI features for each
       - FORBIDDEN: "Company A", "Company B", "Competitor 1", generic placeholders
    
    2. **File: content/{campaign_name}/market_research/keywords.md**
       - Find and compile 20+ specific keywords and search terms
       - Include actual search phrases with quotes like "AI marketing automation"
       - Add search volume data, competition level, related terms
       - FORBIDDEN: "Keyword 1", "Primary keyword", generic terms
    
    3. **File: content/{campaign_name}/market_research/audience.md**
       - Analyze target demographics with specific data
       - Include real demographic data, income ranges, job titles, pain points
       - Add behavioral insights, preferred platforms, buying patterns  
       - FORBIDDEN: "Target segment 1", "Age: 25-45", "Gender: all"
    
    **FILE NAMING VALIDATION:**
    - Files MUST be named exactly: competitors.md, keywords.md, audience.md
    - Files MUST be saved in: content/{campaign_name}/market_research/
    - Do NOT use generic names like "competitors_in_[topic]_market.md"
    
    **RESEARCH APPROACH:**
    - Search for "[topic] competitors 2024" to find real companies
    - Search for "[topic] keywords SEO" to find actual search terms
    - Search for "[target_audience] demographics" for real data
    - Verify all information is current and factual

  expected_output: >
    EXACTLY 3 market research files with verified real competitive intelligence:
    - content/{campaign_name}/market_research/competitors.md (8+ real companies with names, market data, pricing)
    - content/{campaign_name}/market_research/keywords.md (20+ specific search terms with search volume data)
    - content/{campaign_name}/market_research/audience.md (detailed demographics with specific numbers/ranges)
    
    ALL files MUST be created using File Writer Tool with exact names - NO placeholder content accepted.
  agent: market_strategist

market_research_validation_task:
  description: >
    VALIDATION & CORRECTION TASK: Check market research files for placeholder content and fix with real data.
    
    **MANDATORY VALIDATION PROCESS:**
    
    1. Read all 3 market research files:
       - content/{campaign_name}/market_research/competitors.md
       - content/{campaign_name}/market_research/keywords.md
       - content/{campaign_name}/market_research/audience.md
    
    2. Scan for FORBIDDEN placeholder patterns:
       - "Company A", "Company B", "Competitor 1", "Startup X"
       - "Keyword 1", "Primary keyword", generic terms
       - "Segment 1", "Age: 25-45", "Description of"
       - Any vague or template-like content
    
    3. If placeholders found, USE WEB SEARCH to replace with real data:
       - Search for actual companies in the {topic} space
       - Find real keywords with search volumes and competition data
       - Research specific demographic data for {target_audience}
    
    4. Rewrite files with REAL research data:
       - Replace generic "Company A" with "HubSpot Marketing Hub"
       - Replace "Keyword 1" with "AI marketing automation tools"
       - Replace "Age: 25-45" with "Small business owners aged 28-52, average revenue $250K-2M"
    
    **QUALITY STANDARDS:**
    - Every company name must be real and verifiable
    - Every keyword must be specific and searchable
    - Every demographic must include actual numbers/data
    - Content must be actionable for business decisions
    
    **RESEARCH COMMANDS:**
    - Search: "{topic} market leaders 2024"
    - Search: "{topic} software companies"
    - Search: "{topic} SEO keywords high volume"
    - Search: "{target_audience} demographics statistics"

  expected_output: >
    Validated and corrected market research files with 100% real data:
    - competitors.md with verified company names and market intelligence
    - keywords.md with actual search terms and SEO data
    - audience.md with specific demographic statistics and insights
    
    ZERO placeholder content allowed - all data must be real and actionable.
  agent: market_strategist

blog_creation_task:
  description: >
    Create a COMPLETE blog post with ALL required sections about '{topic}' for {target_audience}.
    Voice: {brand_voice}
    
    **CRITICAL FILE REQUIREMENT:**
    You MUST use File Writer Tool to create exactly this file:
    **File Path: content/{campaign_name}/blogs/ai-marketing-guide.md**
    
    **MANDATORY COMPLETE STRUCTURE - ALL SECTIONS REQUIRED:**
    
    1. **Introduction (200+ words)** - Hook for CTOs, establish problem and opportunity
    2. **Main Content Body (1500+ words minimum):**
       - Benefits of cloud computing for e-commerce
       - AI marketing automation advantages  
       - Technical implementation insights
       - ROI and business case with specific metrics
       - Security and scalability considerations
       - Integration challenges and solutions
    3. **Strategic Recommendations (300+ words)** - Actionable next steps for CTOs
    4. **Conclusion (150+ words)** - Summary and call to action
    5. **Additional Resources** - Industry reports, tools, networks
    6. **Glossary of Key Terms** - Technical definitions
    7. **About the Author** - Expert credibility
    
    **CONTENT VALIDATION:**
    - Blog must contain minimum 2000 words of MAIN CONTENT (sections 1-4)
    - Do NOT generate only supplementary sections (5-7) without main content
    - Each section must provide substantial value to technical decision-makers
    - Include specific examples, metrics, and actionable insights
    
    **STRUCTURE REQUIREMENTS:**
    - Use H2 headers (##) for main sections
    - Use H3 headers (###) for subsections  
    - Include bullet points, numbered lists, and tables where appropriate
    - SEO optimized with natural keyword integration
    
    **FAILURE CONDITIONS:**
    - Task FAILS if blog contains only footer sections without main content
    - Task FAILS if word count is under 2000 words total
    - Task FAILS if content lacks technical depth for CTO audience
  expected_output: >
    Complete, publication-ready blog post saved to: content/{campaign_name}/blogs/ai-marketing-guide.md
    Must contain ALL required sections with minimum 2000 words and comprehensive technical insights.
  agent: content_creator

blog_validation_task:
  description: >
    CRITICAL VALIDATION: Verify blog content completeness before proceeding with analysis.
    Read: content/{campaign_name}/blogs/ai-marketing-guide.md
    
    **VALIDATION CHECKLIST:**
    1. Verify blog contains Introduction section (200+ words)
    2. Verify blog contains Main Content Body (1500+ words minimum):
       - Benefits of cloud computing for e-commerce
       - AI marketing automation advantages
       - Technical implementation insights
       - ROI and business case
       - Security and scalability considerations
    3. Verify blog contains Strategic Recommendations (300+ words)
    4. Verify blog contains Conclusion (150+ words)
    5. Check total word count is 2000+ words
    6. Ensure content is NOT just supplementary sections (resources, glossary, author bio)
    
    **FAILURE CONDITIONS:**
    - If blog contains only footer sections without main content, FAIL the validation
    - If word count is under 2000 words, FAIL the validation
    - If missing any required sections, FAIL the validation
    
    **ACTION ON FAILURE:**
    If validation fails, mark task as incomplete and require blog_creation_task to be re-run.
  expected_output: >
    Validation report confirming blog content completeness or flagging specific deficiencies.
  agent: performance_analyst

blog_analysis_task:
  description: >
    Analyze blog post for SEO, conversion, and audience alignment.
    Read: content/{campaign_name}/blogs/ai-marketing-guide.md
    Save analysis to: content/{campaign_name}/analysis/strategic-optimization.md
    
    **PREREQUISITE:** This task can only run after successful blog_validation_task completion.
    
    Cover: SEO optimization, CTAs, audience fit, differentiation, performance predictions.
  expected_output: >
    Strategic analysis with optimization recommendations and performance projections.
  agent: performance_analyst

blog_optimization_task:
  description: >
    Create optimized blog version implementing analysis recommendations.
    Save to: content/{campaign_name}/blogs/optimized-ai-marketing-guide.md
    
    Apply SEO improvements, enhance CTAs, strengthen value delivery, improve readability.
    Maintain {brand_voice} and focus on {topic} for {target_audience}.
  expected_output: >
    Fully optimized blog post with implemented recommendations and superior performance.
  agent: content_creator

distribution_content_creation_task:
  description: >
    Create platform-specific social media posts and email sequence about '{topic}' for {target_audience}.
    Voice: {brand_voice}
    
    **STEP 1:** Read the optimized blog post: content/{campaign_name}/blogs/optimized-ai-marketing-guide.md
    
    **STEP 2:** Create content/{campaign_name}/social-media/posts_v1.md with the following structure:
    
    # Social Media Posts for {topic}
    
    ## LinkedIn Posts
    [3-4 professional LinkedIn posts with 150-300 words each, including hashtags and engagement hooks]
    
    ## Twitter Posts  
    [5-6 Twitter posts under 280 characters, with relevant hashtags and thread potential]
    
    ## Instagram Posts
    [3-4 visual-focused Instagram captions with emojis, hashtags, and story ideas]
    
    ## Facebook Posts
    [3-4 community-focused Facebook posts with engagement questions and shareable content]
    
    **STEP 3:** Create content/{campaign_name}/emails/email-sequence_v1.md with 5-email customer journey sequence
    
    **CRITICAL:** Social media file MUST contain platform-specific posts, NOT blog content. Each platform needs different post styles and lengths.
  expected_output: >
    2 files with platform-specific content:
    - social-media/posts_v1.md (LinkedIn, Twitter, Instagram, Facebook posts with different formats)
    - emails/email-sequence_v1.md (5-email customer journey sequence)
  agent: content_creator

distribution_content_analysis_task:
  description: >
    Analyze social media and email content for optimization opportunities.
    
    Read: content/{campaign_name}/social-media/posts_v1.md and emails/email-sequence_v1.md
    Save to: content/{campaign_name}/analysis/distribution_feedback.md
    
    Cover: engagement potential, CTAs, audience alignment, cross-channel synergy, performance predictions.
  expected_output: >
    Analysis with optimization recommendations and performance projections.
  agent: performance_analyst

distribution_content_optimization_task:
  description: >
    Create optimized platform-specific social media and email content implementing analysis recommendations.
    
    **STEP 1:** Read analysis: content/{campaign_name}/analysis/distribution_feedback.md  
    **STEP 2:** Read originals: content/{campaign_name}/social-media/posts_v1.md and content/{campaign_name}/emails/email-sequence_v1.md
    **STEP 3:** Create optimized versions with same platform-specific structure:
    
    - content/{campaign_name}/social-media/posts_final.md (maintain LinkedIn/Twitter/Instagram/Facebook sections)
    - content/{campaign_name}/emails/email-sequence_final.md (enhanced 5-email sequence)
    
    **CRITICAL:** Maintain platform-specific post formats. Each platform (LinkedIn, Twitter, Instagram, Facebook) needs distinct post styles, lengths, and engagement approaches.
    
    Apply engagement optimizations, enhance CTAs, maintain {brand_voice} and {topic} focus.
  expected_output: >
    2 optimized files with enhanced platform-specific content:
    - social-media/posts_final.md (optimized LinkedIn, Twitter, Instagram, Facebook posts)
    - emails/email-sequence_final.md (enhanced 5-email customer journey sequence)
  agent: content_creator

audio_slogan_task:
  description: >
    Create ONE best Hindi slogan about '{topic}' for {target_audience}. Voice: {brand_voice}
    Save to: content/{campaign_name}/audio/slogans.md
    
    **CRITICAL: GENERATE ONLY ONE BEST SLOGAN - NOT MULTIPLE OPTIONS**
    
    **SELECTION PROCESS (Internal - Do Not Output):**
    1. Internally brainstorm 3-5 slogan concepts using the creative frameworks below
    2. Evaluate each for: memorability, cultural resonance, brand alignment, audio appeal
    3. Select the SINGLE BEST slogan that maximizes impact for {target_audience}
    4. Create audio for only that one chosen slogan
    
    **OUTPUT FORMAT - ONLY ONE SLOGAN:**
    ```
    ## Best Hindi Slogan for {topic}
    
    **Selected Slogan:**
    - **Hindi Text:** "आपका व्यापार, हमारी तकनीक"
    - **Transliteration:** "Aapka vyapar, hamari takneek"  
    - **English Translation:** "Your business, our technology"
    - **Audio:** [filename.wav]
    
    **Selection Rationale:**
    Brief explanation of why this slogan was chosen over alternatives.
    ```
    
    **CREATIVE FRAMEWORKS (For Internal Brainstorming):**

    **1. Transformation Focus:**
    - "Purana tarika chodo, nayi raah banao" (Leave old methods, create new paths)
    - "Mehnat kam, kamyabi zyada" (Less effort, more success)

    **2. Empowerment & Growth:**
    - "Sapno ko haqeeqat banane ka waqt" (Time to make dreams reality)
    - "Technology se tarakki, safalta ki nayi shuruaat" (Progress through technology, new beginning of success)

    **3. Simplicity & Efficiency:**
    - "Smart kaam, smart kamyabi" (Smart work, smart success)
    - "Ek click mein, vyapar ki nayi disha" (One click, new direction for business)

    **4. Innovation & Future:**
    - "Aaj ki technology, kal ki safalta" (Today's technology, tomorrow's success)
    - "AI ke saath, aage badhte chalo" (With AI, keep moving forward)

    **5. ROI & Results:**
    - "Paisa vasool, vyapar bemisaal" (Money well-spent, unmatched business)
    - "Kam paisa, zyada munafa" (Less money, more profit)

    **QUALITY REQUIREMENTS:**
    - Slogan must be 4-8 words maximum for memorability
    - Use rhythm and alliteration for audio appeal
    - Ensure easy pronunciation for non-Hindi speakers
    - Culturally sensitive and business appropriate
    - Maximum emotional impact for {target_audience}
    - Generate professional audio (hi-IN, anushka voice)
    
    **CRITICAL: NO English slogans - ONLY Hindi with transliteration and translation**
    **OUTPUT ONLY THE CHOSEN BEST SLOGAN - NOT MULTIPLE OPTIONS**
  expected_output: >
    ONE best Hindi slogan with transliteration, English translation, selection rationale, and audio generation.
  agent: brand_voice_specialist

audio_slogan_analysis_task:
  description: >
    Analyze Hindi slogans for memorability, cultural impact, and brand alignment.
    
    Read: content/{campaign_name}/audio/slogans.md
    Save to: content/{campaign_name}/analysis/audio_slogan_feedback.md
    
    Cover: memorability, cultural resonance, brand alignment, market effectiveness, audio quality.
  expected_output: >
    Analysis with slogan optimization recommendations and deployment strategy.
  agent: performance_analyst

final_report_assembly_task:
  description: >
    Create executive campaign report about '{topic}' for {target_audience}.
    Save to: content/{campaign_name}/FINAL_CAMPAIGN_REPORT.md
    
    Include: Executive summary, market insights, content showcase, performance projections, 
    implementation roadmap, success metrics, strategic recommendations.
    Professional format suitable for stakeholders.
  expected_output: >
    Comprehensive executive campaign report with strategic implementation guidance.
  agent: campaign_manager
